version: '3.8'

services:
  db:
    image: postgres:15
    container_name: trcklist-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DATABASE}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    mem_limit: 300m

  app:
    build: .
    container_name: trcklist-api
    depends_on:
      - db
    environment:
      DATABASE_URL: ${DATABASE_URL_DOCKER}
      JWT_SECRET: ${JWT_SECRET}
    ports:
      - "4001:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: sh -c "npx prisma migrate deploy && npm run start"
    mem_limit: 500m

volumes:
  pgdata:
